project_id = "bdtjpegklvjjuifpsikg"

[functions.update-rental-location]
verify_jwt = false

[functions.extend_rental_time]
verify_jwt = false

[functions.create-payment-link]
verify_jwt = true

[functions.payment-webhook]
verify_jwt = false

[functions.cancel-subscription]
verify_jwt = true

[functions.verify-payment-status]
verify_jwt = true

[functions.verify-admin-password]
verify_jwt = true

[functions.list-user-billings]
verify_jwt = true
